#!/bin/bash
RM="rm -rf"
find . -name *.o -exec rm {} \;
find . -name *.ali -exec rm {} \;
find . -name *.stderr -exec rm {} \;
$RM compilers/iac/backend-be_corba_ada-nodes.idl-stamp
$RM compilers/iac/frontend-nodes.idl-stamp
$RM autom4te.cache
$RM compilers/gnatprfh/gnatprfh
$RM compilers/iac/iac
$RM compilers/iac/backend-be_corba_ada-nodes.adb
$RM compilers/iac/backend-be_corba_ada-nodes.ads
$RM compilers/iac/frontend-nodes.adb
$RM compilers/iac/frontend-nodes.ads
$RM compilers/iac/mknodes
$RM config.excluded_source_files
$RM config.local.makefiles
$RM config.log
$RM config.platform_base_withs.adb
$RM config.po_catref_withs.adb
$RM config.po_createref_withs.adb
$RM config.proto_client_withs.adb
$RM config.proto_server_withs.adb
$RM config.status
$RM cos/ir/polyorb-corba-cos-ir-impl.lexch
$RM cos/naming/polyorb-corba-cos-naming-impl.lexch
$RM idls/cos/naming/polyorb-corba-cos-naming.lexch
$RM src/config.h
$RM src/corba/dynamicany/polyorb-corba-dynamicany.lexch
$RM src/corba/iop/polyorb-corba-iop.lexch
$RM src/corba/messaging/
$RM src/corba/polyorb-corba.lexch
$RM src/corba/portableinterceptor/polyorb-corba-portableinterceptor.lexch
$RM src/corba/rtcorba/polyorb-corba-rtcorba.lexch
$RM src/dsa/polyorb-dsa.lexch
$RM src/giop/diop/polyorb-giop-diop.lexch
$RM src/giop/iiop/polyorb-giop-iiop.lexch
$RM src/giop/miop/polyorb-giop-miop.lexch
$RM src/giop/polyorb-giop.lexch
$RM src/polyorb-smart_pointers-sync_counters.adb
$RM src/polyorb.lexch
$RM src/setup/polyorb-setup.lexch
$RM src/soap/polyorb-soap.lexch
$RM src/stamp-h1
$RM src/web_common/polyorb-web_common.lexch
$RM testsuite/projects/polyorb_common.gpr
$RM testsuite/projects/polyorb_config.gpr
$RM tools/po_ir/po_ir
$RM Makefile
$RM Makefile.common
$RM Makefile.common.project
$RM compilers/common_files/platform.ads
$RM compilers/config.adc
$RM compilers/gnatdist/xe_defs-defaults.ads
$RM compilers/gnatprfh/gnatprfh.adb
$RM config.platform_base_withs.adb
$RM contrib/idlac_wrapper/idlac_wrapper
$RM doc/Makefile
$RM doc/polyorb_version.py
$RM examples/corba/secure_echo/gssup.conf
$RM examples/corba/secure_echo/tls.conf
$RM examples/corba/secure_echo/tls_gssup.conf
$RM polyorb-config
$RM projects-distrib/polyorb.gpr
$RM projects-distrib/polyorb/polyorb_install_common.gpr
$RM projects-distrib/polyorb/polyorb_src_setup.gpr
$RM projects/polyorb.gpr
$RM projects/polyorb_config.gpr
$RM projects/polyorb_src_setup.gpr
$RM src/config.adc
$RM src/polyorb-platform-ssl_linker_options.ads
$RM src/polyorb-platform.ads
$RM src/ravenscar.adc
$RM src/ravenscar_compatible.adc
$RM src/setup/polyorb-setup-base.adb
$RM src/setup/polyorb-setup-client_base.adb
$RM src/setup/polyorb-setup-server.adb
$RM src/setup/polyorb-setup-tasking-full_tasking.adb
$RM src/src.exclude
$RM testsuite/tests/config.py
$RM tools/po_catref/po_catref_setup.adb
$RM tools/po_createref/po_createref_setup.adb
$RM 1
$RM ali/
$RM compilers/gnatdist/b__po_gnatdist.adb
$RM compilers/gnatdist/b__po_gnatdist.ads
$RM compilers/gnatdist/po_gnatdist
$RM cos/event/coseventchanneladmin-consumeradmin-skel.adb
$RM cos/event/coseventchanneladmin-consumeradmin-skel.ads
$RM cos/event/coseventchanneladmin-eventchannel-skel.adb
$RM cos/event/coseventchanneladmin-eventchannel-skel.ads
$RM cos/event/coseventchanneladmin-proxypullconsumer-skel.adb
$RM cos/event/coseventchanneladmin-proxypullconsumer-skel.ads
$RM cos/event/coseventchanneladmin-proxypullsupplier-skel.adb
$RM cos/event/coseventchanneladmin-proxypullsupplier-skel.ads
$RM cos/event/coseventchanneladmin-proxypushconsumer-skel.adb
$RM cos/event/coseventchanneladmin-proxypushconsumer-skel.ads
$RM cos/event/coseventchanneladmin-proxypushsupplier-skel.adb
$RM cos/event/coseventchanneladmin-proxypushsupplier-skel.ads
$RM cos/event/coseventchanneladmin-supplieradmin-skel.adb
$RM cos/event/coseventchanneladmin-supplieradmin-skel.ads
$RM cos/event/coseventchanneladmin_consumeradmin_hash.adb
$RM cos/event/coseventchanneladmin_consumeradmin_hash.ads
$RM cos/event/coseventchanneladmin_eventchannel_hash.adb
$RM cos/event/coseventchanneladmin_eventchannel_hash.ads
$RM cos/event/coseventchanneladmin_proxypullconsumer_hash.adb
$RM cos/event/coseventchanneladmin_proxypullconsumer_hash.ads
$RM cos/event/coseventchanneladmin_proxypullsupplier_hash.adb
$RM cos/event/coseventchanneladmin_proxypullsupplier_hash.ads
$RM cos/event/coseventchanneladmin_proxypushconsumer_hash.adb
$RM cos/event/coseventchanneladmin_proxypushconsumer_hash.ads
$RM cos/event/coseventchanneladmin_proxypushsupplier_hash.adb
$RM cos/event/coseventchanneladmin_proxypushsupplier_hash.ads
$RM cos/event/coseventchanneladmin_supplieradmin_hash.adb
$RM cos/event/coseventchanneladmin_supplieradmin_hash.ads
$RM cos/event/coseventcomm-pullconsumer-skel.adb
$RM cos/event/coseventcomm-pullconsumer-skel.ads
$RM cos/event/coseventcomm-pullsupplier-skel.adb
$RM cos/event/coseventcomm-pullsupplier-skel.ads
$RM cos/event/coseventcomm-pushconsumer-skel.adb
$RM cos/event/coseventcomm-pushconsumer-skel.ads
$RM cos/event/coseventcomm-pushsupplier-skel.adb
$RM cos/event/coseventcomm-pushsupplier-skel.ads
$RM cos/event/coseventcomm_pullconsumer_hash.adb
$RM cos/event/coseventcomm_pullconsumer_hash.ads
$RM cos/event/coseventcomm_pullsupplier_hash.adb
$RM cos/event/coseventcomm_pullsupplier_hash.ads
$RM cos/event/coseventcomm_pushconsumer_hash.adb
$RM cos/event/coseventcomm_pushconsumer_hash.ads
$RM cos/event/coseventcomm_pushsupplier_hash.adb
$RM cos/event/coseventcomm_pushsupplier_hash.ads
$RM cos/event/costypedeventchanneladmin-typedconsumeradmin-skel.adb
$RM cos/event/costypedeventchanneladmin-typedconsumeradmin-skel.ads
$RM cos/event/costypedeventchanneladmin-typedeventchannel-skel.adb
$RM cos/event/costypedeventchanneladmin-typedeventchannel-skel.ads
$RM cos/event/costypedeventchanneladmin-typedproxypullsupplier-skel.adb
$RM cos/event/costypedeventchanneladmin-typedproxypullsupplier-skel.ads
$RM cos/event/costypedeventchanneladmin-typedproxypushconsumer-skel.adb
$RM cos/event/costypedeventchanneladmin-typedproxypushconsumer-skel.ads
$RM cos/event/costypedeventchanneladmin-typedsupplieradmin-skel.adb
$RM cos/event/costypedeventchanneladmin-typedsupplieradmin-skel.ads
$RM cos/event/costypedeventchanneladmin_typedconsumeradmin_hash.adb
$RM cos/event/costypedeventchanneladmin_typedconsumeradmin_hash.ads
$RM cos/event/costypedeventchanneladmin_typedeventchannel_hash.adb
$RM cos/event/costypedeventchanneladmin_typedeventchannel_hash.ads
$RM cos/event/costypedeventchanneladmin_typedproxypullsupplier_hash.adb
$RM cos/event/costypedeventchanneladmin_typedproxypullsupplier_hash.ads
$RM cos/event/costypedeventchanneladmin_typedproxypushconsumer_hash.adb
$RM cos/event/costypedeventchanneladmin_typedproxypushconsumer_hash.ads
$RM cos/event/costypedeventchanneladmin_typedsupplieradmin_hash.adb
$RM cos/event/costypedeventchanneladmin_typedsupplieradmin_hash.ads
$RM cos/event/costypedeventcomm-typedpullsupplier-skel.adb
$RM cos/event/costypedeventcomm-typedpullsupplier-skel.ads
$RM cos/event/costypedeventcomm-typedpushconsumer-skel.adb
$RM cos/event/costypedeventcomm-typedpushconsumer-skel.ads
$RM cos/event/costypedeventcomm_typedpullsupplier_hash.adb
$RM cos/event/costypedeventcomm_typedpullsupplier_hash.ads
$RM cos/event/costypedeventcomm_typedpushconsumer_hash.adb
$RM cos/event/costypedeventcomm_typedpushconsumer_hash.ads
$RM cos/ir/corba-repository_root-abstractinterfacedef-helper.adb
$RM cos/ir/corba-repository_root-abstractinterfacedef-helper.ads
$RM cos/ir/corba-repository_root-abstractinterfacedef-skel.adb
$RM cos/ir/corba-repository_root-abstractinterfacedef-skel.ads
$RM cos/ir/corba-repository_root-abstractinterfacedef.adb
$RM cos/ir/corba-repository_root-abstractinterfacedef.ads
$RM cos/ir/corba-repository_root-aliasdef-helper.adb
$RM cos/ir/corba-repository_root-aliasdef-helper.ads
$RM cos/ir/corba-repository_root-aliasdef-skel.adb
$RM cos/ir/corba-repository_root-aliasdef-skel.ads
$RM cos/ir/corba-repository_root-aliasdef.adb
$RM cos/ir/corba-repository_root-aliasdef.ads
$RM cos/ir/corba-repository_root-arraydef-helper.adb
$RM cos/ir/corba-repository_root-arraydef-helper.ads
$RM cos/ir/corba-repository_root-arraydef-skel.adb
$RM cos/ir/corba-repository_root-arraydef-skel.ads
$RM cos/ir/corba-repository_root-arraydef.adb
$RM cos/ir/corba-repository_root-arraydef.ads
$RM cos/ir/corba-repository_root-attributedef-helper.adb
$RM cos/ir/corba-repository_root-attributedef-helper.ads
$RM cos/ir/corba-repository_root-attributedef-skel.adb
$RM cos/ir/corba-repository_root-attributedef-skel.ads
$RM cos/ir/corba-repository_root-attributedef.adb
$RM cos/ir/corba-repository_root-attributedef.ads
$RM cos/ir/corba-repository_root-constantdef-helper.adb
$RM cos/ir/corba-repository_root-constantdef-helper.ads
$RM cos/ir/corba-repository_root-constantdef-skel.adb
$RM cos/ir/corba-repository_root-constantdef-skel.ads
$RM cos/ir/corba-repository_root-constantdef.adb
$RM cos/ir/corba-repository_root-constantdef.ads
$RM cos/ir/corba-repository_root-contained-helper.adb
$RM cos/ir/corba-repository_root-contained-helper.ads
$RM cos/ir/corba-repository_root-contained-skel.adb
$RM cos/ir/corba-repository_root-contained-skel.ads
$RM cos/ir/corba-repository_root-contained.adb
$RM cos/ir/corba-repository_root-contained.ads
$RM cos/ir/corba-repository_root-container-helper.adb
$RM cos/ir/corba-repository_root-container-helper.ads
$RM cos/ir/corba-repository_root-container-skel.adb
$RM cos/ir/corba-repository_root-container-skel.ads
$RM cos/ir/corba-repository_root-container.adb
$RM cos/ir/corba-repository_root-container.ads
$RM cos/ir/corba-repository_root-enumdef-helper.adb
$RM cos/ir/corba-repository_root-enumdef-helper.ads
$RM cos/ir/corba-repository_root-enumdef-skel.adb
$RM cos/ir/corba-repository_root-enumdef-skel.ads
$RM cos/ir/corba-repository_root-enumdef.adb
$RM cos/ir/corba-repository_root-enumdef.ads
$RM cos/ir/corba-repository_root-exceptiondef-helper.adb
$RM cos/ir/corba-repository_root-exceptiondef-helper.ads
$RM cos/ir/corba-repository_root-exceptiondef-skel.adb
$RM cos/ir/corba-repository_root-exceptiondef-skel.ads
$RM cos/ir/corba-repository_root-exceptiondef.adb
$RM cos/ir/corba-repository_root-exceptiondef.ads
$RM cos/ir/corba-repository_root-extabstractinterfacedef-helper.adb
$RM cos/ir/corba-repository_root-extabstractinterfacedef-helper.ads
$RM cos/ir/corba-repository_root-extabstractinterfacedef-skel.adb
$RM cos/ir/corba-repository_root-extabstractinterfacedef-skel.ads
$RM cos/ir/corba-repository_root-extabstractinterfacedef.adb
$RM cos/ir/corba-repository_root-extabstractinterfacedef.ads
$RM cos/ir/corba-repository_root-extattributedef-helper.adb
$RM cos/ir/corba-repository_root-extattributedef-helper.ads
$RM cos/ir/corba-repository_root-extattributedef-skel.adb
$RM cos/ir/corba-repository_root-extattributedef-skel.ads
$RM cos/ir/corba-repository_root-extattributedef.adb
$RM cos/ir/corba-repository_root-extattributedef.ads
$RM cos/ir/corba-repository_root-extinterfacedef-helper.adb
$RM cos/ir/corba-repository_root-extinterfacedef-helper.ads
$RM cos/ir/corba-repository_root-extinterfacedef-skel.adb
$RM cos/ir/corba-repository_root-extinterfacedef-skel.ads
$RM cos/ir/corba-repository_root-extinterfacedef.adb
$RM cos/ir/corba-repository_root-extinterfacedef.ads
$RM cos/ir/corba-repository_root-extlocalinterfacedef-helper.adb
$RM cos/ir/corba-repository_root-extlocalinterfacedef-helper.ads
$RM cos/ir/corba-repository_root-extlocalinterfacedef-skel.adb
$RM cos/ir/corba-repository_root-extlocalinterfacedef-skel.ads
$RM cos/ir/corba-repository_root-extlocalinterfacedef.adb
$RM cos/ir/corba-repository_root-extlocalinterfacedef.ads
$RM cos/ir/corba-repository_root-fixeddef-helper.adb
$RM cos/ir/corba-repository_root-fixeddef-helper.ads
$RM cos/ir/corba-repository_root-fixeddef-skel.adb
$RM cos/ir/corba-repository_root-fixeddef-skel.ads
$RM cos/ir/corba-repository_root-fixeddef.adb
$RM cos/ir/corba-repository_root-fixeddef.ads
$RM cos/ir/corba-repository_root-helper.adb
$RM cos/ir/corba-repository_root-helper.ads
$RM cos/ir/corba-repository_root-idltype-helper.adb
$RM cos/ir/corba-repository_root-idltype-helper.ads
$RM cos/ir/corba-repository_root-idltype-skel.adb
$RM cos/ir/corba-repository_root-idltype-skel.ads
$RM cos/ir/corba-repository_root-idltype.adb
$RM cos/ir/corba-repository_root-idltype.ads
$RM cos/ir/corba-repository_root-interfaceattrextension-helper.adb
$RM cos/ir/corba-repository_root-interfaceattrextension-helper.ads
$RM cos/ir/corba-repository_root-interfaceattrextension-skel.adb
$RM cos/ir/corba-repository_root-interfaceattrextension-skel.ads
$RM cos/ir/corba-repository_root-interfaceattrextension.adb
$RM cos/ir/corba-repository_root-interfaceattrextension.ads
$RM cos/ir/corba-repository_root-interfacedef-helper.adb
$RM cos/ir/corba-repository_root-interfacedef-helper.ads
$RM cos/ir/corba-repository_root-interfacedef-skel.adb
$RM cos/ir/corba-repository_root-interfacedef-skel.ads
$RM cos/ir/corba-repository_root-interfacedef.adb
$RM cos/ir/corba-repository_root-interfacedef.ads
$RM cos/ir/corba-repository_root-irobject-helper.adb
$RM cos/ir/corba-repository_root-irobject-helper.ads
$RM cos/ir/corba-repository_root-irobject-skel.adb
$RM cos/ir/corba-repository_root-irobject-skel.ads
$RM cos/ir/corba-repository_root-irobject.adb
$RM cos/ir/corba-repository_root-irobject.ads
$RM cos/ir/corba-repository_root-localinterfacedef-helper.adb
$RM cos/ir/corba-repository_root-localinterfacedef-helper.ads
$RM cos/ir/corba-repository_root-localinterfacedef-skel.adb
$RM cos/ir/corba-repository_root-localinterfacedef-skel.ads
$RM cos/ir/corba-repository_root-localinterfacedef.adb
$RM cos/ir/corba-repository_root-localinterfacedef.ads
$RM cos/ir/corba-repository_root-moduledef-helper.adb
$RM cos/ir/corba-repository_root-moduledef-helper.ads
$RM cos/ir/corba-repository_root-moduledef-skel.adb
$RM cos/ir/corba-repository_root-moduledef-skel.ads
$RM cos/ir/corba-repository_root-moduledef.adb
$RM cos/ir/corba-repository_root-moduledef.ads
$RM cos/ir/corba-repository_root-nativedef-helper.adb
$RM cos/ir/corba-repository_root-nativedef-helper.ads
$RM cos/ir/corba-repository_root-nativedef-skel.adb
$RM cos/ir/corba-repository_root-nativedef-skel.ads
$RM cos/ir/corba-repository_root-nativedef.adb
$RM cos/ir/corba-repository_root-nativedef.ads
$RM cos/ir/corba-repository_root-operationdef-helper.adb
$RM cos/ir/corba-repository_root-operationdef-helper.ads
$RM cos/ir/corba-repository_root-operationdef-skel.adb
$RM cos/ir/corba-repository_root-operationdef-skel.ads
$RM cos/ir/corba-repository_root-operationdef.adb
$RM cos/ir/corba-repository_root-operationdef.ads
$RM cos/ir/corba-repository_root-primitivedef-helper.adb
$RM cos/ir/corba-repository_root-primitivedef-helper.ads
$RM cos/ir/corba-repository_root-primitivedef-skel.adb
$RM cos/ir/corba-repository_root-primitivedef-skel.ads
$RM cos/ir/corba-repository_root-primitivedef.adb
$RM cos/ir/corba-repository_root-primitivedef.ads
$RM cos/ir/corba-repository_root-repository-helper.adb
$RM cos/ir/corba-repository_root-repository-helper.ads
$RM cos/ir/corba-repository_root-repository-skel.adb
$RM cos/ir/corba-repository_root-repository-skel.ads
$RM cos/ir/corba-repository_root-repository.adb
$RM cos/ir/corba-repository_root-repository.ads
$RM cos/ir/corba-repository_root-sequencedef-helper.adb
$RM cos/ir/corba-repository_root-sequencedef-helper.ads
$RM cos/ir/corba-repository_root-sequencedef-skel.adb
$RM cos/ir/corba-repository_root-sequencedef-skel.ads
$RM cos/ir/corba-repository_root-sequencedef.adb
$RM cos/ir/corba-repository_root-sequencedef.ads
$RM cos/ir/corba-repository_root-stringdef-helper.adb
$RM cos/ir/corba-repository_root-stringdef-helper.ads
$RM cos/ir/corba-repository_root-stringdef-skel.adb
$RM cos/ir/corba-repository_root-stringdef-skel.ads
$RM cos/ir/corba-repository_root-stringdef.adb
$RM cos/ir/corba-repository_root-stringdef.ads
$RM cos/ir/corba-repository_root-structdef-helper.adb
$RM cos/ir/corba-repository_root-structdef-helper.ads
$RM cos/ir/corba-repository_root-structdef-skel.adb
$RM cos/ir/corba-repository_root-structdef-skel.ads
$RM cos/ir/corba-repository_root-structdef.adb
$RM cos/ir/corba-repository_root-structdef.ads
$RM cos/ir/corba-repository_root-typedefdef-helper.adb
$RM cos/ir/corba-repository_root-typedefdef-helper.ads
$RM cos/ir/corba-repository_root-typedefdef-skel.adb
$RM cos/ir/corba-repository_root-typedefdef-skel.ads
$RM cos/ir/corba-repository_root-typedefdef.adb
$RM cos/ir/corba-repository_root-typedefdef.ads
$RM cos/ir/corba-repository_root-uniondef-helper.adb
$RM cos/ir/corba-repository_root-uniondef-helper.ads
$RM cos/ir/corba-repository_root-uniondef-skel.adb
$RM cos/ir/corba-repository_root-uniondef-skel.ads
$RM cos/ir/corba-repository_root-uniondef.adb
$RM cos/ir/corba-repository_root-uniondef.ads
$RM cos/ir/corba-repository_root-valueboxdef-helper.adb
$RM cos/ir/corba-repository_root-valueboxdef-helper.ads
$RM cos/ir/corba-repository_root-valueboxdef-skel.adb
$RM cos/ir/corba-repository_root-valueboxdef-skel.ads
$RM cos/ir/corba-repository_root-valueboxdef.adb
$RM cos/ir/corba-repository_root-valueboxdef.ads
$RM cos/ir/corba-repository_root-valuedef-helper.adb
$RM cos/ir/corba-repository_root-valuedef-helper.ads
$RM cos/ir/corba-repository_root-valuedef-skel.adb
$RM cos/ir/corba-repository_root-valuedef-skel.ads
$RM cos/ir/corba-repository_root-valuedef.adb
$RM cos/ir/corba-repository_root-valuedef.ads
$RM cos/ir/corba-repository_root-valuememberdef-helper.adb
$RM cos/ir/corba-repository_root-valuememberdef-helper.ads
$RM cos/ir/corba-repository_root-valuememberdef-skel.adb
$RM cos/ir/corba-repository_root-valuememberdef-skel.ads
$RM cos/ir/corba-repository_root-valuememberdef.adb
$RM cos/ir/corba-repository_root-valuememberdef.ads
$RM cos/ir/corba-repository_root-wstringdef-helper.adb
$RM cos/ir/corba-repository_root-wstringdef-helper.ads
$RM cos/ir/corba-repository_root-wstringdef-skel.adb
$RM cos/ir/corba-repository_root-wstringdef-skel.ads
$RM cos/ir/corba-repository_root-wstringdef.adb
$RM cos/ir/corba-repository_root-wstringdef.ads
$RM cos/ir/corba_repository_root_abstractinterfacedef_hash.adb
$RM cos/ir/corba_repository_root_abstractinterfacedef_hash.ads
$RM cos/ir/corba_repository_root_aliasdef_hash.adb
$RM cos/ir/corba_repository_root_aliasdef_hash.ads
$RM cos/ir/corba_repository_root_arraydef_hash.adb
$RM cos/ir/corba_repository_root_arraydef_hash.ads
$RM cos/ir/corba_repository_root_attributedef_hash.adb
$RM cos/ir/corba_repository_root_attributedef_hash.ads
$RM cos/ir/corba_repository_root_constantdef_hash.adb
$RM cos/ir/corba_repository_root_constantdef_hash.ads
$RM cos/ir/corba_repository_root_contained_hash.adb
$RM cos/ir/corba_repository_root_contained_hash.ads
$RM cos/ir/corba_repository_root_container_hash.adb
$RM cos/ir/corba_repository_root_container_hash.ads
$RM cos/ir/corba_repository_root_enumdef_hash.adb
$RM cos/ir/corba_repository_root_enumdef_hash.ads
$RM cos/ir/corba_repository_root_exceptiondef_hash.adb
$RM cos/ir/corba_repository_root_exceptiondef_hash.ads
$RM cos/ir/corba_repository_root_extabstractinterfacedef_hash.adb
$RM cos/ir/corba_repository_root_extabstractinterfacedef_hash.ads
$RM cos/ir/corba_repository_root_extattributedef_hash.adb
$RM cos/ir/corba_repository_root_extattributedef_hash.ads
$RM cos/ir/corba_repository_root_extinterfacedef_hash.adb
$RM cos/ir/corba_repository_root_extinterfacedef_hash.ads
$RM cos/ir/corba_repository_root_extlocalinterfacedef_hash.adb
$RM cos/ir/corba_repository_root_extlocalinterfacedef_hash.ads
$RM cos/ir/corba_repository_root_fixeddef_hash.adb
$RM cos/ir/corba_repository_root_fixeddef_hash.ads
$RM cos/ir/corba_repository_root_idltype_hash.adb
$RM cos/ir/corba_repository_root_idltype_hash.ads
$RM cos/ir/corba_repository_root_interfaceattrextension_hash.adb
$RM cos/ir/corba_repository_root_interfaceattrextension_hash.ads
$RM cos/ir/corba_repository_root_interfacedef_hash.adb
$RM cos/ir/corba_repository_root_interfacedef_hash.ads
$RM cos/ir/corba_repository_root_irobject_hash.adb
$RM cos/ir/corba_repository_root_irobject_hash.ads
$RM cos/ir/corba_repository_root_localinterfacedef_hash.adb
$RM cos/ir/corba_repository_root_localinterfacedef_hash.ads
$RM cos/ir/corba_repository_root_moduledef_hash.adb
$RM cos/ir/corba_repository_root_moduledef_hash.ads
$RM cos/ir/corba_repository_root_nativedef_hash.adb
$RM cos/ir/corba_repository_root_nativedef_hash.ads
$RM cos/ir/corba_repository_root_operationdef_hash.adb
$RM cos/ir/corba_repository_root_operationdef_hash.ads
$RM cos/ir/corba_repository_root_primitivedef_hash.adb
$RM cos/ir/corba_repository_root_primitivedef_hash.ads
$RM cos/ir/corba_repository_root_repository_hash.adb
$RM cos/ir/corba_repository_root_repository_hash.ads
$RM cos/ir/corba_repository_root_sequencedef_hash.adb
$RM cos/ir/corba_repository_root_sequencedef_hash.ads
$RM cos/ir/corba_repository_root_stringdef_hash.adb
$RM cos/ir/corba_repository_root_stringdef_hash.ads
$RM cos/ir/corba_repository_root_structdef_hash.adb
$RM cos/ir/corba_repository_root_structdef_hash.ads
$RM cos/ir/corba_repository_root_typedefdef_hash.adb
$RM cos/ir/corba_repository_root_typedefdef_hash.ads
$RM cos/ir/corba_repository_root_uniondef_hash.adb
$RM cos/ir/corba_repository_root_uniondef_hash.ads
$RM cos/ir/corba_repository_root_valueboxdef_hash.adb
$RM cos/ir/corba_repository_root_valueboxdef_hash.ads
$RM cos/ir/corba_repository_root_valuedef_hash.adb
$RM cos/ir/corba_repository_root_valuedef_hash.ads
$RM cos/ir/corba_repository_root_valuememberdef_hash.adb
$RM cos/ir/corba_repository_root_valuememberdef_hash.ads
$RM cos/ir/corba_repository_root_wstringdef_hash.adb
$RM cos/ir/corba_repository_root_wstringdef_hash.ads
$RM cos/naming/cosnaming-bindingiterator-skel.adb
$RM cos/naming/cosnaming-bindingiterator-skel.ads
$RM cos/naming/cosnaming-namingcontext-skel.adb
$RM cos/naming/cosnaming-namingcontext-skel.ads
$RM cos/naming/cosnaming-namingcontextext-skel.adb
$RM cos/naming/cosnaming-namingcontextext-skel.ads
$RM cos/naming/cosnaming_bindingiterator_hash.adb
$RM cos/naming/cosnaming_bindingiterator_hash.ads
$RM cos/naming/cosnaming_namingcontext_hash.adb
$RM cos/naming/cosnaming_namingcontext_hash.ads
$RM cos/naming/cosnaming_namingcontextext_hash.adb
$RM cos/naming/cosnaming_namingcontextext_hash.ads
$RM cos/naming/file-helper.adb
$RM cos/naming/file-helper.ads
$RM cos/naming/file-skel.adb
$RM cos/naming/file-skel.ads
$RM cos/naming/file.adb
$RM cos/naming/file.ads
$RM cos/naming/file_hash.adb
$RM cos/naming/file_hash.ads
$RM cos/notification/cosnotification-adminpropertiesadmin-skel.adb
$RM cos/notification/cosnotification-adminpropertiesadmin-skel.ads
$RM cos/notification/cosnotification-qosadmin-skel.adb
$RM cos/notification/cosnotification-qosadmin-skel.ads
$RM cos/notification/cosnotification_adminpropertiesadmin_hash.adb
$RM cos/notification/cosnotification_adminpropertiesadmin_hash.ads
$RM cos/notification/cosnotification_qosadmin_hash.adb
$RM cos/notification/cosnotification_qosadmin_hash.ads
$RM cos/notification/cosnotifychanneladmin-consumeradmin-skel.adb
$RM cos/notification/cosnotifychanneladmin-consumeradmin-skel.ads
$RM cos/notification/cosnotifychanneladmin-eventchannel-skel.adb
$RM cos/notification/cosnotifychanneladmin-eventchannel-skel.ads
$RM cos/notification/cosnotifychanneladmin-eventchannelfactory-skel.adb
$RM cos/notification/cosnotifychanneladmin-eventchannelfactory-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxyconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxyconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxypullconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxypullconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxypullsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxypullsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxypushconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxypushconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxypushsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxypushsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-proxysupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-proxysupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-structuredproxypullconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-structuredproxypullconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-structuredproxypullsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-structuredproxypullsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-structuredproxypushconsumer-skel.adb
$RM cos/notification/cosnotifychanneladmin-structuredproxypushconsumer-skel.ads
$RM cos/notification/cosnotifychanneladmin-structuredproxypushsupplier-skel.adb
$RM cos/notification/cosnotifychanneladmin-structuredproxypushsupplier-skel.ads
$RM cos/notification/cosnotifychanneladmin-supplieradmin-skel.adb
$RM cos/notification/cosnotifychanneladmin-supplieradmin-skel.ads
$RM cos/notification/cosnotifychanneladmin_consumeradmin_hash.adb
$RM cos/notification/cosnotifychanneladmin_consumeradmin_hash.ads
$RM cos/notification/cosnotifychanneladmin_eventchannel_hash.adb
$RM cos/notification/cosnotifychanneladmin_eventchannel_hash.ads
$RM cos/notification/cosnotifychanneladmin_eventchannelfactory_hash.adb
$RM cos/notification/cosnotifychanneladmin_eventchannelfactory_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxyconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxyconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxypullconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxypullconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxypullsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxypullsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxypushconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxypushconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxypushsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxypushsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_proxysupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_proxysupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_sequenceproxypullconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_sequenceproxypullconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_sequenceproxypullsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_sequenceproxypullsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_sequenceproxypushconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_sequenceproxypushconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_sequenceproxypushsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_sequenceproxypushsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_structuredproxypullconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_structuredproxypullconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_structuredproxypullsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_structuredproxypullsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_structuredproxypushconsumer_hash.adb
$RM cos/notification/cosnotifychanneladmin_structuredproxypushconsumer_hash.ads
$RM cos/notification/cosnotifychanneladmin_structuredproxypushsupplier_hash.adb
$RM cos/notification/cosnotifychanneladmin_structuredproxypushsupplier_hash.ads
$RM cos/notification/cosnotifychanneladmin_supplieradmin_hash.adb
$RM cos/notification/cosnotifychanneladmin_supplieradmin_hash.ads
$RM cos/notification/cosnotifycomm-notifypublish-skel.adb
$RM cos/notification/cosnotifycomm-notifypublish-skel.ads
$RM cos/notification/cosnotifycomm-notifysubscribe-skel.adb
$RM cos/notification/cosnotifycomm-notifysubscribe-skel.ads
$RM cos/notification/cosnotifycomm-pullconsumer-skel.adb
$RM cos/notification/cosnotifycomm-pullconsumer-skel.ads
$RM cos/notification/cosnotifycomm-pullsupplier-skel.adb
$RM cos/notification/cosnotifycomm-pullsupplier-skel.ads
$RM cos/notification/cosnotifycomm-pushconsumer-skel.adb
$RM cos/notification/cosnotifycomm-pushconsumer-skel.ads
$RM cos/notification/cosnotifycomm-pushsupplier-skel.adb
$RM cos/notification/cosnotifycomm-pushsupplier-skel.ads
$RM cos/notification/cosnotifycomm-sequencepullconsumer-skel.adb
$RM cos/notification/cosnotifycomm-sequencepullconsumer-skel.ads
$RM cos/notification/cosnotifycomm-sequencepullsupplier-skel.adb
$RM cos/notification/cosnotifycomm-sequencepullsupplier-skel.ads
$RM cos/notification/cosnotifycomm-sequencepushconsumer-skel.adb
$RM cos/notification/cosnotifycomm-sequencepushconsumer-skel.ads
$RM cos/notification/cosnotifycomm-sequencepushsupplier-skel.adb
$RM cos/notification/cosnotifycomm-sequencepushsupplier-skel.ads
$RM cos/notification/cosnotifycomm-structuredpullconsumer-skel.adb
$RM cos/notification/cosnotifycomm-structuredpullconsumer-skel.ads
$RM cos/notification/cosnotifycomm-structuredpullsupplier-skel.adb
$RM cos/notification/cosnotifycomm-structuredpullsupplier-skel.ads
$RM cos/notification/cosnotifycomm-structuredpushconsumer-skel.adb
$RM cos/notification/cosnotifycomm-structuredpushconsumer-skel.ads
$RM cos/notification/cosnotifycomm-structuredpushsupplier-skel.adb
$RM cos/notification/cosnotifycomm-structuredpushsupplier-skel.ads
$RM cos/notification/cosnotifycomm_notifypublish_hash.adb
$RM cos/notification/cosnotifycomm_notifypublish_hash.ads
$RM cos/notification/cosnotifycomm_notifysubscribe_hash.adb
$RM cos/notification/cosnotifycomm_notifysubscribe_hash.ads
$RM cos/notification/cosnotifycomm_pullconsumer_hash.adb
$RM cos/notification/cosnotifycomm_pullconsumer_hash.ads
$RM cos/notification/cosnotifycomm_pullsupplier_hash.adb
$RM cos/notification/cosnotifycomm_pullsupplier_hash.ads
$RM cos/notification/cosnotifycomm_pushconsumer_hash.adb
$RM cos/notification/cosnotifycomm_pushconsumer_hash.ads
$RM cos/notification/cosnotifycomm_pushsupplier_hash.adb
$RM cos/notification/cosnotifycomm_pushsupplier_hash.ads
$RM cos/notification/cosnotifycomm_sequencepullconsumer_hash.adb
$RM cos/notification/cosnotifycomm_sequencepullconsumer_hash.ads
$RM cos/notification/cosnotifycomm_sequencepullsupplier_hash.adb
$RM cos/notification/cosnotifycomm_sequencepullsupplier_hash.ads
$RM cos/notification/cosnotifycomm_sequencepushconsumer_hash.adb
$RM cos/notification/cosnotifycomm_sequencepushconsumer_hash.ads
$RM cos/notification/cosnotifycomm_sequencepushsupplier_hash.adb
$RM cos/notification/cosnotifycomm_sequencepushsupplier_hash.ads
$RM cos/notification/cosnotifycomm_structuredpullconsumer_hash.adb
$RM cos/notification/cosnotifycomm_structuredpullconsumer_hash.ads
$RM cos/notification/cosnotifycomm_structuredpullsupplier_hash.adb
$RM cos/notification/cosnotifycomm_structuredpullsupplier_hash.ads
$RM cos/notification/cosnotifycomm_structuredpushconsumer_hash.adb
$RM cos/notification/cosnotifycomm_structuredpushconsumer_hash.ads
$RM cos/notification/cosnotifycomm_structuredpushsupplier_hash.adb
$RM cos/notification/cosnotifycomm_structuredpushsupplier_hash.ads
$RM cos/notification/cosnotifyfilter-filter-skel.adb
$RM cos/notification/cosnotifyfilter-filter-skel.ads
$RM cos/notification/cosnotifyfilter-filteradmin-skel.adb
$RM cos/notification/cosnotifyfilter-filteradmin-skel.ads
$RM cos/notification/cosnotifyfilter-filterfactory-skel.adb
$RM cos/notification/cosnotifyfilter-filterfactory-skel.ads
$RM cos/notification/cosnotifyfilter-mappingfilter-skel.adb
$RM cos/notification/cosnotifyfilter-mappingfilter-skel.ads
$RM cos/notification/cosnotifyfilter_filter_hash.adb
$RM cos/notification/cosnotifyfilter_filter_hash.ads
$RM cos/notification/cosnotifyfilter_filteradmin_hash.adb
$RM cos/notification/cosnotifyfilter_filteradmin_hash.ads
$RM cos/notification/cosnotifyfilter_filterfactory_hash.adb
$RM cos/notification/cosnotifyfilter_filterfactory_hash.ads
$RM cos/notification/cosnotifyfilter_mappingfilter_hash.adb
$RM cos/notification/cosnotifyfilter_mappingfilter_hash.ads
$RM cos/time/costime-timeservice-skel.adb
$RM cos/time/costime-timeservice-skel.ads
$RM cos/time/costime-tio-skel.adb
$RM cos/time/costime-tio-skel.ads
$RM cos/time/costime-uto-skel.adb
$RM cos/time/costime-uto-skel.ads
$RM cos/time/costime_timeservice_hash.adb
$RM cos/time/costime_timeservice_hash.ads
$RM cos/time/costime_tio_hash.adb
$RM cos/time/costime_tio_hash.ads
$RM cos/time/costime_uto_hash.adb
$RM cos/time/costime_uto_hash.ads
$RM idls/cos/event/coseventchanneladmin-consumeradmin-helper.adb
$RM idls/cos/event/coseventchanneladmin-consumeradmin-helper.ads
$RM idls/cos/event/coseventchanneladmin-consumeradmin.adb
$RM idls/cos/event/coseventchanneladmin-consumeradmin.ads
$RM idls/cos/event/coseventchanneladmin-eventchannel-helper.adb
$RM idls/cos/event/coseventchanneladmin-eventchannel-helper.ads
$RM idls/cos/event/coseventchanneladmin-eventchannel.adb
$RM idls/cos/event/coseventchanneladmin-eventchannel.ads
$RM idls/cos/event/coseventchanneladmin-helper.adb
$RM idls/cos/event/coseventchanneladmin-helper.ads
$RM idls/cos/event/coseventchanneladmin-proxypullconsumer-helper.adb
$RM idls/cos/event/coseventchanneladmin-proxypullconsumer-helper.ads
$RM idls/cos/event/coseventchanneladmin-proxypullconsumer.adb
$RM idls/cos/event/coseventchanneladmin-proxypullconsumer.ads
$RM idls/cos/event/coseventchanneladmin-proxypullsupplier-helper.adb
$RM idls/cos/event/coseventchanneladmin-proxypullsupplier-helper.ads
$RM idls/cos/event/coseventchanneladmin-proxypullsupplier.adb
$RM idls/cos/event/coseventchanneladmin-proxypullsupplier.ads
$RM idls/cos/event/coseventchanneladmin-proxypushconsumer-helper.adb
$RM idls/cos/event/coseventchanneladmin-proxypushconsumer-helper.ads
$RM idls/cos/event/coseventchanneladmin-proxypushconsumer.adb
$RM idls/cos/event/coseventchanneladmin-proxypushconsumer.ads
$RM idls/cos/event/coseventchanneladmin-proxypushsupplier-helper.adb
$RM idls/cos/event/coseventchanneladmin-proxypushsupplier-helper.ads
$RM idls/cos/event/coseventchanneladmin-proxypushsupplier.adb
$RM idls/cos/event/coseventchanneladmin-proxypushsupplier.ads
$RM idls/cos/event/coseventchanneladmin-supplieradmin-helper.adb
$RM idls/cos/event/coseventchanneladmin-supplieradmin-helper.ads
$RM idls/cos/event/coseventchanneladmin-supplieradmin.adb
$RM idls/cos/event/coseventchanneladmin-supplieradmin.ads
$RM idls/cos/event/coseventchanneladmin.adb
$RM idls/cos/event/coseventchanneladmin.ads
$RM idls/cos/event/coseventcomm-helper.adb
$RM idls/cos/event/coseventcomm-helper.ads
$RM idls/cos/event/coseventcomm-pullconsumer-helper.adb
$RM idls/cos/event/coseventcomm-pullconsumer-helper.ads
$RM idls/cos/event/coseventcomm-pullconsumer.adb
$RM idls/cos/event/coseventcomm-pullconsumer.ads
$RM idls/cos/event/coseventcomm-pullsupplier-helper.adb
$RM idls/cos/event/coseventcomm-pullsupplier-helper.ads
$RM idls/cos/event/coseventcomm-pullsupplier.adb
$RM idls/cos/event/coseventcomm-pullsupplier.ads
$RM idls/cos/event/coseventcomm-pushconsumer-helper.adb
$RM idls/cos/event/coseventcomm-pushconsumer-helper.ads
$RM idls/cos/event/coseventcomm-pushconsumer.adb
$RM idls/cos/event/coseventcomm-pushconsumer.ads
$RM idls/cos/event/coseventcomm-pushsupplier-helper.adb
$RM idls/cos/event/coseventcomm-pushsupplier-helper.ads
$RM idls/cos/event/coseventcomm-pushsupplier.adb
$RM idls/cos/event/coseventcomm-pushsupplier.ads
$RM idls/cos/event/coseventcomm.adb
$RM idls/cos/event/coseventcomm.ads
$RM idls/cos/event/costypedeventchanneladmin-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedconsumeradmin-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-typedconsumeradmin-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedconsumeradmin.adb
$RM idls/cos/event/costypedeventchanneladmin-typedconsumeradmin.ads
$RM idls/cos/event/costypedeventchanneladmin-typedeventchannel-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-typedeventchannel-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedeventchannel.adb
$RM idls/cos/event/costypedeventchanneladmin-typedeventchannel.ads
$RM idls/cos/event/costypedeventchanneladmin-typedproxypullsupplier-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-typedproxypullsupplier-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedproxypullsupplier.adb
$RM idls/cos/event/costypedeventchanneladmin-typedproxypullsupplier.ads
$RM idls/cos/event/costypedeventchanneladmin-typedproxypushconsumer-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-typedproxypushconsumer-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedproxypushconsumer.adb
$RM idls/cos/event/costypedeventchanneladmin-typedproxypushconsumer.ads
$RM idls/cos/event/costypedeventchanneladmin-typedsupplieradmin-helper.adb
$RM idls/cos/event/costypedeventchanneladmin-typedsupplieradmin-helper.ads
$RM idls/cos/event/costypedeventchanneladmin-typedsupplieradmin.adb
$RM idls/cos/event/costypedeventchanneladmin-typedsupplieradmin.ads
$RM idls/cos/event/costypedeventchanneladmin.adb
$RM idls/cos/event/costypedeventchanneladmin.ads
$RM idls/cos/event/costypedeventcomm-typedpullsupplier-helper.adb
$RM idls/cos/event/costypedeventcomm-typedpullsupplier-helper.ads
$RM idls/cos/event/costypedeventcomm-typedpullsupplier.adb
$RM idls/cos/event/costypedeventcomm-typedpullsupplier.ads
$RM idls/cos/event/costypedeventcomm-typedpushconsumer-helper.adb
$RM idls/cos/event/costypedeventcomm-typedpushconsumer-helper.ads
$RM idls/cos/event/costypedeventcomm-typedpushconsumer.adb
$RM idls/cos/event/costypedeventcomm-typedpushconsumer.ads
$RM idls/cos/event/costypedeventcomm.ads
$RM idls/cos/naming/cosnaming-bindingiterator-helper.adb
$RM idls/cos/naming/cosnaming-bindingiterator-helper.ads
$RM idls/cos/naming/cosnaming-bindingiterator.adb
$RM idls/cos/naming/cosnaming-bindingiterator.ads
$RM idls/cos/naming/cosnaming-helper.adb
$RM idls/cos/naming/cosnaming-helper.ads
$RM idls/cos/naming/cosnaming-namingcontext-helper.adb
$RM idls/cos/naming/cosnaming-namingcontext-helper.ads
$RM idls/cos/naming/cosnaming-namingcontext.adb
$RM idls/cos/naming/cosnaming-namingcontext.ads
$RM idls/cos/naming/cosnaming-namingcontextext-helper.adb
$RM idls/cos/naming/cosnaming-namingcontextext-helper.ads
$RM idls/cos/naming/cosnaming-namingcontextext.adb
$RM idls/cos/naming/cosnaming-namingcontextext.ads
$RM idls/cos/naming/cosnaming.ads
$RM idls/cos/notification/cosnotification-adminpropertiesadmin-helper.adb
$RM idls/cos/notification/cosnotification-adminpropertiesadmin-helper.ads
$RM idls/cos/notification/cosnotification-adminpropertiesadmin.adb
$RM idls/cos/notification/cosnotification-adminpropertiesadmin.ads
$RM idls/cos/notification/cosnotification-helper.adb
$RM idls/cos/notification/cosnotification-helper.ads
$RM idls/cos/notification/cosnotification-qosadmin-helper.adb
$RM idls/cos/notification/cosnotification-qosadmin-helper.ads
$RM idls/cos/notification/cosnotification-qosadmin.adb
$RM idls/cos/notification/cosnotification-qosadmin.ads
$RM idls/cos/notification/cosnotification.adb
$RM idls/cos/notification/cosnotification.ads
$RM idls/cos/notification/cosnotifychanneladmin-consumeradmin-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-consumeradmin-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-consumeradmin.adb
$RM idls/cos/notification/cosnotifychanneladmin-consumeradmin.ads
$RM idls/cos/notification/cosnotifychanneladmin-eventchannel-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-eventchannel-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-eventchannel.adb
$RM idls/cos/notification/cosnotifychanneladmin-eventchannel.ads
$RM idls/cos/notification/cosnotifychanneladmin-eventchannelfactory-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-eventchannelfactory-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-eventchannelfactory.adb
$RM idls/cos/notification/cosnotifychanneladmin-eventchannelfactory.ads
$RM idls/cos/notification/cosnotifychanneladmin-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxyconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxyconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxyconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxyconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypullconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypullconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypullconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypullconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypullsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypullsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypullsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypullsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypushconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypushconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypushconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypushconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypushsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypushsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxypushsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxypushsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxysupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxysupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-proxysupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-proxysupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypullsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-sequenceproxypushsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypullsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushconsumer-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushconsumer-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushconsumer.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushconsumer.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushsupplier-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushsupplier-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushsupplier.adb
$RM idls/cos/notification/cosnotifychanneladmin-structuredproxypushsupplier.ads
$RM idls/cos/notification/cosnotifychanneladmin-supplieradmin-helper.adb
$RM idls/cos/notification/cosnotifychanneladmin-supplieradmin-helper.ads
$RM idls/cos/notification/cosnotifychanneladmin-supplieradmin.adb
$RM idls/cos/notification/cosnotifychanneladmin-supplieradmin.ads
$RM idls/cos/notification/cosnotifychanneladmin.adb
$RM idls/cos/notification/cosnotifychanneladmin.ads
$RM idls/cos/notification/cosnotifycomm-helper.adb
$RM idls/cos/notification/cosnotifycomm-helper.ads
$RM idls/cos/notification/cosnotifycomm-notifypublish-helper.adb
$RM idls/cos/notification/cosnotifycomm-notifypublish-helper.ads
$RM idls/cos/notification/cosnotifycomm-notifypublish.adb
$RM idls/cos/notification/cosnotifycomm-notifypublish.ads
$RM idls/cos/notification/cosnotifycomm-notifysubscribe-helper.adb
$RM idls/cos/notification/cosnotifycomm-notifysubscribe-helper.ads
$RM idls/cos/notification/cosnotifycomm-notifysubscribe.adb
$RM idls/cos/notification/cosnotifycomm-notifysubscribe.ads
$RM idls/cos/notification/cosnotifycomm-pullconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-pullconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-pullconsumer.adb
$RM idls/cos/notification/cosnotifycomm-pullconsumer.ads
$RM idls/cos/notification/cosnotifycomm-pullsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-pullsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-pullsupplier.adb
$RM idls/cos/notification/cosnotifycomm-pullsupplier.ads
$RM idls/cos/notification/cosnotifycomm-pushconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-pushconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-pushconsumer.adb
$RM idls/cos/notification/cosnotifycomm-pushconsumer.ads
$RM idls/cos/notification/cosnotifycomm-pushsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-pushsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-pushsupplier.adb
$RM idls/cos/notification/cosnotifycomm-pushsupplier.ads
$RM idls/cos/notification/cosnotifycomm-sequencepullconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-sequencepullconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-sequencepullconsumer.adb
$RM idls/cos/notification/cosnotifycomm-sequencepullconsumer.ads
$RM idls/cos/notification/cosnotifycomm-sequencepullsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-sequencepullsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-sequencepullsupplier.adb
$RM idls/cos/notification/cosnotifycomm-sequencepullsupplier.ads
$RM idls/cos/notification/cosnotifycomm-sequencepushconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-sequencepushconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-sequencepushconsumer.adb
$RM idls/cos/notification/cosnotifycomm-sequencepushconsumer.ads
$RM idls/cos/notification/cosnotifycomm-sequencepushsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-sequencepushsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-sequencepushsupplier.adb
$RM idls/cos/notification/cosnotifycomm-sequencepushsupplier.ads
$RM idls/cos/notification/cosnotifycomm-structuredpullconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-structuredpullconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-structuredpullconsumer.adb
$RM idls/cos/notification/cosnotifycomm-structuredpullconsumer.ads
$RM idls/cos/notification/cosnotifycomm-structuredpullsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-structuredpullsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-structuredpullsupplier.adb
$RM idls/cos/notification/cosnotifycomm-structuredpullsupplier.ads
$RM idls/cos/notification/cosnotifycomm-structuredpushconsumer-helper.adb
$RM idls/cos/notification/cosnotifycomm-structuredpushconsumer-helper.ads
$RM idls/cos/notification/cosnotifycomm-structuredpushconsumer.adb
$RM idls/cos/notification/cosnotifycomm-structuredpushconsumer.ads
$RM idls/cos/notification/cosnotifycomm-structuredpushsupplier-helper.adb
$RM idls/cos/notification/cosnotifycomm-structuredpushsupplier-helper.ads
$RM idls/cos/notification/cosnotifycomm-structuredpushsupplier.adb
$RM idls/cos/notification/cosnotifycomm-structuredpushsupplier.ads
$RM idls/cos/notification/cosnotifycomm.adb
$RM idls/cos/notification/cosnotifycomm.ads
$RM idls/cos/notification/cosnotifyfilter-filter-helper.adb
$RM idls/cos/notification/cosnotifyfilter-filter-helper.ads
$RM idls/cos/notification/cosnotifyfilter-filter.adb
$RM idls/cos/notification/cosnotifyfilter-filter.ads
$RM idls/cos/notification/cosnotifyfilter-filteradmin-helper.adb
$RM idls/cos/notification/cosnotifyfilter-filteradmin-helper.ads
$RM idls/cos/notification/cosnotifyfilter-filteradmin.adb
$RM idls/cos/notification/cosnotifyfilter-filteradmin.ads
$RM idls/cos/notification/cosnotifyfilter-filterfactory-helper.adb
$RM idls/cos/notification/cosnotifyfilter-filterfactory-helper.ads
$RM idls/cos/notification/cosnotifyfilter-filterfactory.adb
$RM idls/cos/notification/cosnotifyfilter-filterfactory.ads
$RM idls/cos/notification/cosnotifyfilter-helper.adb
$RM idls/cos/notification/cosnotifyfilter-helper.ads
$RM idls/cos/notification/cosnotifyfilter-mappingfilter-helper.adb
$RM idls/cos/notification/cosnotifyfilter-mappingfilter-helper.ads
$RM idls/cos/notification/cosnotifyfilter-mappingfilter.adb
$RM idls/cos/notification/cosnotifyfilter-mappingfilter.ads
$RM idls/cos/notification/cosnotifyfilter.adb
$RM idls/cos/notification/cosnotifyfilter.ads
$RM idls/cos/time/costime-helper.adb
$RM idls/cos/time/costime-helper.ads
$RM idls/cos/time/costime-timeservice-helper.adb
$RM idls/cos/time/costime-timeservice-helper.ads
$RM idls/cos/time/costime-timeservice.adb
$RM idls/cos/time/costime-timeservice.ads
$RM idls/cos/time/costime-tio-helper.adb
$RM idls/cos/time/costime-tio-helper.ads
$RM idls/cos/time/costime-tio.adb
$RM idls/cos/time/costime-tio.ads
$RM idls/cos/time/costime-uto-helper.adb
$RM idls/cos/time/costime-uto-helper.ads
$RM idls/cos/time/costime-uto.adb
$RM idls/cos/time/costime-uto.ads
$RM idls/cos/time/costime.adb
$RM idls/cos/time/costime.ads
$RM idls/cos/time/timebase-helper.adb
$RM idls/cos/time/timebase-helper.ads
$RM idls/cos/time/timebase.ads
$RM lib/
$RM src/corba/conv_frame-helper.adb
$RM src/corba/conv_frame-helper.ads
$RM src/corba/conv_frame.ads
$RM src/corba/dynamicany/dynamicany-dynany-helper.adb
$RM src/corba/dynamicany/dynamicany-dynany-helper.ads
$RM src/corba/dynamicany/dynamicany-dynany.adb
$RM src/corba/dynamicany/dynamicany-dynany.ads
$RM src/corba/dynamicany/dynamicany-dynanyfactory-helper.adb
$RM src/corba/dynamicany/dynamicany-dynanyfactory-helper.ads
$RM src/corba/dynamicany/dynamicany-dynanyfactory.adb
$RM src/corba/dynamicany/dynamicany-dynanyfactory.ads
$RM src/corba/dynamicany/dynamicany-dynarray-helper.adb
$RM src/corba/dynamicany/dynamicany-dynarray-helper.ads
$RM src/corba/dynamicany/dynamicany-dynarray.adb
$RM src/corba/dynamicany/dynamicany-dynarray.ads
$RM src/corba/dynamicany/dynamicany-dynenum-helper.adb
$RM src/corba/dynamicany/dynamicany-dynenum-helper.ads
$RM src/corba/dynamicany/dynamicany-dynenum.adb
$RM src/corba/dynamicany/dynamicany-dynenum.ads
$RM src/corba/dynamicany/dynamicany-dynfixed-helper.adb
$RM src/corba/dynamicany/dynamicany-dynfixed-helper.ads
$RM src/corba/dynamicany/dynamicany-dynfixed.adb
$RM src/corba/dynamicany/dynamicany-dynfixed.ads
$RM src/corba/dynamicany/dynamicany-dynsequence-helper.adb
$RM src/corba/dynamicany/dynamicany-dynsequence-helper.ads
$RM src/corba/dynamicany/dynamicany-dynsequence.adb
$RM src/corba/dynamicany/dynamicany-dynsequence.ads
$RM src/corba/dynamicany/dynamicany-dynstruct-helper.adb
$RM src/corba/dynamicany/dynamicany-dynstruct-helper.ads
$RM src/corba/dynamicany/dynamicany-dynstruct.adb
$RM src/corba/dynamicany/dynamicany-dynstruct.ads
$RM src/corba/dynamicany/dynamicany-dynunion-helper.adb
$RM src/corba/dynamicany/dynamicany-dynunion-helper.ads
$RM src/corba/dynamicany/dynamicany-dynunion.adb
$RM src/corba/dynamicany/dynamicany-dynunion.ads
$RM src/corba/dynamicany/dynamicany-dynvalue-helper.adb
$RM src/corba/dynamicany/dynamicany-dynvalue-helper.ads
$RM src/corba/dynamicany/dynamicany-dynvalue.adb
$RM src/corba/dynamicany/dynamicany-dynvalue.ads
$RM src/corba/dynamicany/dynamicany-dynvaluebox-helper.adb
$RM src/corba/dynamicany/dynamicany-dynvaluebox-helper.ads
$RM src/corba/dynamicany/dynamicany-dynvaluebox.adb
$RM src/corba/dynamicany/dynamicany-dynvaluebox.ads
$RM src/corba/dynamicany/dynamicany-dynvaluecommon-helper.adb
$RM src/corba/dynamicany/dynamicany-dynvaluecommon-helper.ads
$RM src/corba/dynamicany/dynamicany-dynvaluecommon.adb
$RM src/corba/dynamicany/dynamicany-dynvaluecommon.ads
$RM src/corba/dynamicany/dynamicany-helper.adb
$RM src/corba/dynamicany/dynamicany-helper.ads
$RM src/corba/dynamicany/dynamicany.adb
$RM src/corba/dynamicany/dynamicany.ads
$RM src/corba/iop/iop-codec-helper.adb
$RM src/corba/iop/iop-codec-helper.ads
$RM src/corba/iop/iop-codec.adb
$RM src/corba/iop/iop-codec.ads
$RM src/corba/iop/iop-codecfactory-helper.adb
$RM src/corba/iop/iop-codecfactory-helper.ads
$RM src/corba/iop/iop-codecfactory.adb
$RM src/corba/iop/iop-codecfactory.ads
$RM src/corba/iop/iop-helper.adb
$RM src/corba/iop/iop-helper.ads
$RM src/corba/iop/iop.ads
$RM src/corba/portableinterceptor/dynamic-helper.adb
$RM src/corba/portableinterceptor/dynamic-helper.ads
$RM src/corba/portableinterceptor/dynamic.ads
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinfo-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinfo-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinfo.adb
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinfo.ads
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinterceptor-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinterceptor-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinterceptor.adb
$RM src/corba/portableinterceptor/portableinterceptor-clientrequestinterceptor.ads
$RM src/corba/portableinterceptor/portableinterceptor-current-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-current-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-current.adb
$RM src/corba/portableinterceptor/portableinterceptor-current.ads
$RM src/corba/portableinterceptor/portableinterceptor-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-interceptor-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-interceptor-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-interceptor.adb
$RM src/corba/portableinterceptor/portableinterceptor-interceptor.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinfo-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinfo-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinfo.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinfo.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor_3_0-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor_3_0-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor_3_0.adb
$RM src/corba/portableinterceptor/portableinterceptor-iorinterceptor_3_0.ads
$RM src/corba/portableinterceptor/portableinterceptor-orbinitializer-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-orbinitializer-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-orbinitializer.adb
$RM src/corba/portableinterceptor/portableinterceptor-orbinitializer.ads
$RM src/corba/portableinterceptor/portableinterceptor-orbinitinfo-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-orbinitinfo-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-orbinitinfo.adb
$RM src/corba/portableinterceptor/portableinterceptor-orbinitinfo.ads
$RM src/corba/portableinterceptor/portableinterceptor-policyfactory-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-policyfactory-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-policyfactory.adb
$RM src/corba/portableinterceptor/portableinterceptor-policyfactory.ads
$RM src/corba/portableinterceptor/portableinterceptor-requestinfo-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-requestinfo-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-requestinfo.adb
$RM src/corba/portableinterceptor/portableinterceptor-requestinfo.ads
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinfo-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinfo-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinfo.adb
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinfo.ads
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinterceptor-helper.adb
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinterceptor-helper.ads
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinterceptor.adb
$RM src/corba/portableinterceptor/portableinterceptor-serverrequestinterceptor.ads
$RM src/corba/portableinterceptor/portableinterceptor.adb
$RM src/corba/portableinterceptor/portableinterceptor.ads
$RM src/corba/rtcorba/rtcosscheduling-clientscheduler-helper.adb
$RM src/corba/rtcorba/rtcosscheduling-clientscheduler-helper.ads
$RM src/corba/rtcorba/rtcosscheduling-clientscheduler.adb
$RM src/corba/rtcorba/rtcosscheduling-clientscheduler.ads
$RM src/corba/rtcorba/rtcosscheduling-helper.adb
$RM src/corba/rtcorba/rtcosscheduling-helper.ads
$RM src/corba/rtcorba/rtcosscheduling-serverscheduler-helper.adb
$RM src/corba/rtcorba/rtcosscheduling-serverscheduler-helper.ads
$RM src/corba/rtcorba/rtcosscheduling-serverscheduler.adb
$RM src/corba/rtcorba/rtcosscheduling-serverscheduler.ads
$RM src/corba/rtcorba/rtcosscheduling.adb
$RM src/corba/rtcorba/rtcosscheduling.ads
$RM src/corba/security/csi-helper.adb
$RM src/corba/security/csi-helper.ads
$RM src/corba/security/csi.ads
$RM src/corba/security/csiiop-helper.adb
$RM src/corba/security/csiiop-helper.ads
$RM src/corba/security/csiiop.ads
$RM src/corba/security/gssup/
$RM src/giop/polyorb-giop_p-code_sets-data.ads
$RM src/giop/tools/gen_codeset
$RM src/mkdir.flag
$RM src/soap/perfect_hash.adb
$RM src/soap/perfect_hash.ads
$RM src/soap/polyorb-http_headers.adb
$RM src/soap/polyorb-http_methods.adb
$RM tools/po_catref/b__po_catref-main.adb
$RM tools/po_catref/b__po_catref-main.ads
$RM tools/po_catref/po_catref
$RM tools/po_catref/polyorb-giop_p-code_sets-description_data.ads
$RM tools/po_cos_naming/b__ir_ab_names.adb
$RM tools/po_cos_naming/b__ir_ab_names.ads
$RM tools/po_cos_naming/b__po_cos_naming.adb
$RM tools/po_cos_naming/b__po_cos_naming.ads
$RM tools/po_cos_naming/b__po_cos_naming_shell.adb
$RM tools/po_cos_naming/b__po_cos_naming_shell.ads
$RM tools/po_cos_naming/ir_ab_names
$RM tools/po_cos_naming/po_cos_naming
$RM tools/po_cos_naming/po_cos_naming_shell
$RM tools/po_createref/b__po_createref.adb
$RM tools/po_createref/b__po_createref.ads
$RM tools/po_createref/po_createref
$RM tools/po_dumpir/b__po_dumpir.adb
$RM tools/po_dumpir/b__po_dumpir.ads
$RM tools/po_dumpir/po_dumpir
$RM tools/po_ir/b__po_ir.adb
$RM tools/po_ir/b__po_ir.ads
$RM tools/po_names/b__po_names.adb
$RM tools/po_names/b__po_names.ads
$RM tools/po_names/po_names
