#!/bin/bash
RM="rm -rf"
find . -name *.o -exec rm {} \;
find . -name *.ali -exec rm {} \;
find . -name *.stderr -exec rm {} \;
$RM compilers/iac/backend-be_corba_ada-nodes.idl-stamp
$RM compilers/iac/frontend-nodes.idl-stamp
$RM autom4te.cache
$RM compilers/gnatprfh/gnatprfh
$RM compilers/iac/iac
$RM compilers/iac/backend-be_corba_ada-nodes.adb
$RM compilers/iac/backend-be_corba_ada-nodes.ads
$RM compilers/iac/frontend-nodes.adb
$RM compilers/iac/frontend-nodes.ads
$RM compilers/iac/mknodes
$RM config.excluded_source_files
$RM config.local.makefiles
$RM config.log
$RM config.platform_base_withs.adb
$RM config.po_catref_withs.adb
$RM config.po_createref_withs.adb
$RM config.proto_client_withs.adb
$RM config.proto_server_withs.adb
$RM config.status
$RM cos/ir/polyorb-corba-cos-ir-impl.lexch
$RM cos/naming/polyorb-corba-cos-naming-impl.lexch
$RM idls/cos/naming/polyorb-corba-cos-naming.lexch
$RM src/config.h
$RM src/corba/dynamicany/polyorb-corba-dynamicany.lexch
$RM src/corba/iop/polyorb-corba-iop.lexch
$RM src/corba/messaging/
$RM src/corba/polyorb-corba.lexch
$RM src/corba/portableinterceptor/polyorb-corba-portableinterceptor.lexch
$RM src/corba/rtcorba/polyorb-corba-rtcorba.lexch
$RM src/dsa/polyorb-dsa.lexch
$RM src/giop/diop/polyorb-giop-diop.lexch
$RM src/giop/iiop/polyorb-giop-iiop.lexch
$RM src/giop/miop/polyorb-giop-miop.lexch
$RM src/giop/polyorb-giop.lexch
$RM src/polyorb-smart_pointers-sync_counters.adb
$RM src/polyorb.lexch
$RM src/setup/polyorb-setup.lexch
$RM src/soap/polyorb-soap.lexch
$RM src/stamp-h1
$RM src/web_common/polyorb-web_common.lexch
$RM testsuite/projects/polyorb_common.gpr
$RM testsuite/projects/polyorb_config.gpr
$RM tools/po_ir/po_ir
$RM Makefile
$RM Makefile.common
$RM Makefile.common.project
$RM compilers/common_files/platform.ads
$RM compilers/config.adc
$RM compilers/gnatdist/xe_defs-defaults.ads
$RM compilers/gnatprfh/gnatprfh.adb
$RM config.platform_base_withs.adb
$RM contrib/idlac_wrapper/idlac_wrapper
$RM doc/Makefile
$RM doc/polyorb_version.py
$RM examples/corba/secure_echo/gssup.conf
$RM examples/corba/secure_echo/tls.conf
$RM examples/corba/secure_echo/tls_gssup.conf
$RM polyorb-config
$RM projects-distrib/polyorb.gpr
$RM projects-distrib/polyorb/polyorb_install_common.gpr
$RM projects-distrib/polyorb/polyorb_src_setup.gpr
$RM projects/polyorb.gpr
$RM projects/polyorb_config.gpr
$RM projects/polyorb_src_setup.gpr
$RM src/config.adc
$RM src/polyorb-platform-ssl_linker_options.ads
$RM src/polyorb-platform.ads
$RM src/ravenscar.adc
$RM src/ravenscar_compatible.adc
$RM src/setup/polyorb-setup-base.adb
$RM src/setup/polyorb-setup-client_base.adb
$RM src/setup/polyorb-setup-server.adb
$RM src/setup/polyorb-setup-tasking-full_tasking.adb
$RM src/src.exclude
$RM testsuite/tests/config.py
$RM tools/po_catref/po_catref_setup.adb
$RM tools/po_createref/po_createref_setup.adb

